apiVersion: v1
kind: Service
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  creationTimestamp: null
  labels:
    app: oracle
  name: oracle
spec:
  ports:
  - name: 22-tcp
    port: 22
    protocol: TCP
    targetPort: 22
  - name: 1521-tcp
    port: 1521
    protocol: TCP
    targetPort: 1521
  - name: 8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: oracle
    deploymentconfig: oracle
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
